config/routes.rb
Rails.application.routes.draw do
  devise_for :shops, controllers: {
    sessions: 'shops/sessions',
    passwords: 'shops/passwords',
    registrations: 'shops/registrations'
  }
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    passwords: 'users/passwords',
    registrations: 'users/registrations'
  }


  #userサイト
  root 'public/users#top'
  put '/user' => 'public/users#destroy'
  scope module: :public do
    #idが必要ないと考えた為、単数形resource
    resource :user, only: [:show, :edit, :update] do
      collection do
        get 'cancel'
        get 'about'
      end
    end

    resources :post_images, only: [:index, :show] do
      resource :reservations, only: [:create] do
        collection do
          get 'finish'
        end
      end
      resource :comments, only: [:create]
      resource :favorites, only: [:create, :destroy]
    end

    #shop_idが必要だった為、contact/bookingをネスト(6/1)
    resources :shops, only: [:index, :show] do
      resource :contacts, only: [:new, :create] do
        collection do
          get 'finish'
        end
      end
      resources :bookings, only: [:new, :create] do
        collection do
          get 'finish'
        end
      end
    end

  end

  #shopサイト
  namespace :admin do
    #idが必要ないと考えた為、単数形resource
    resource :shop, only: [:show, :edit, :update, :destroy] do
      collection do
        get 'cancel'
      end
    end

    resources :post_images, only: [:new, :create, :show, :edit, :update]

    resources :reservations, only: [:index]

    resources :bookings, only: [:index]

    resources :contacts, only: [:index]
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/shop.rb
class Shop < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  #relations
  has_many :post_images, dependent: :destroy
  has_many :contacts, dependent: :destroy
  has_many :bookings, dependent: :destroy
  has_many :reservations, dependent: :destroy

  #画像投稿メソッド
  attachment :profile_image

  #with_optionsを用いてvalidates付与
  with_options presence: true do |s|
  	s.validates :name
  	s.validates :postal_code
  	s.validates :address
  end
  #日本の郵便番号は7桁
  validates :postal_code, format: { with: /\A\d{7}\z/}


end

app/controllers/admin/shops_controller.rb
class Admin::ShopsController < ApplicationController
  def show
  	@shop = Shop.find(current_shop.id)
    #.order(created_at: :desc)で新着順に
    @post_images = PostImage.where(shop_id: current_shop.id).order(created_at: :desc)
  end

  def edit
  	@shop = Shop.find(current_shop.id)
  end

  def update
  	@shop = Shop.find(current_shop.id)
  	@shop.update(shop_params)
  	redirect_to admin_shop_path
  end

  def cancel
  end

  private

  def shop_params
  	params.require(:shop).permit(:name, :email, :postal_code, :address, :profile_image)
  end

end

app/controllers/shops/registrations_controller.rb
# frozen_string_literal: true

class Shops::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end

  #新規会員登録後のリダイレクト先をマイページに変更
  def after_sign_up_path_for(resource)
    admin_shop_path
  end
end

app/controllers/shops/sessions_controller.rb
# frozen_string_literal: true

class Shops::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end

  #ログイン後のリダイレクト先をマイページに変更
  def after_sign_in_path_for(resource)
    admin_shop_path
  end
end

app/helpers/admin/shops_helper.rb
module Admin::ShopsHelper
end

app/views/admin/shops/cancel.html.erb
<div class="container">
	<div class="row">
		<div class="col"></div>
		<div class="col-10">
			<%# 退会メッセージ %>
			<div class="finish-message mt-5 text-center">
				<h1>本当に退会しますか？</h1>
				<br>
				<p>
					退会すると、会員登録情報や<br>
					これまでの投稿等が全て削除されます。<br>
					退会する場合は下記の退会するボタンをクリックしてください。
				</p>
			</div>

			<div class="btns text-center">
				<%# 退会せずに、マイページにリダイレクト %>
				<%= link_to "退会しない", admin_shop_path, class: "btn btn-primary" %>
				<%# 退会後、topページにリダイレクト %>
				<%= link_to "退会する", "/shops", method: :delete, class: "btn btn-danger" %>
			</div>
		</div>
		<div class="col"></div>
	</div>
</div>

app/views/admin/shops/edit.html.erb
<div class="container">
    <div class="row">
        <div class="col"></div>

        <div class="col-8 mt-4">
            <h2>登録情報編集</h2>

            <%# デフォルトのaction設定でuserサイトのshop詳細に遷移してしまうので、urlで保存先を指定 %>
            <%= form_for(@shop, url: admin_shop_path) do |f| %>

                <div class="row mt-5">
                    <div class="col">
                        <%= attachment_image_tag @shop, :profile_image, format: "jpg", fallback: "no_image.png", size:'300x300', class: "rounded-circle border" %>
                    </div>

                    <div class="col">
                        <%# 画像ファイル追加 %>
                        <div class="row">
                            <div class="col-5">
                                <%= f.label :profile_image, "画像ファイル" %>
                            </div>
                            <div class="col-7">
                                <%= f.attachment_field :profile_image %>
                            </div>
                        </div>
                        <%# 店舗名登録 %>
                        <div class="row mt-3">
                            <div class="col-5">
                                <%= f.label :name, "店舗名" %>
                            </div>
                            <div class="col-7">
                                <%= f.text_field :name, autofocus: true %>
                            </div>
                        </div>

                        <%# メールアドレス登録  %>
                        <div class="row mt-3">
                            <div class="col-5">
                                <%= f.label :email, "メールアドレス" %>
                            </div>
                            <div class="col-7">
                                <%= f.email_field :email, autocomplete: "email" %>
                            </div>
                        </div>

                        <%# 郵便番号登録 %>
                        <div class="row mt-3">
                            <div class="col-5">
                                <%= f.label :postal_code, "郵便番号" %>
                            </div>
                            <div class="col-7">
                                <%= f.text_field :postal_code %>
                            </div>
                        </div>

                        <%# 住所登録 %>
                        <div class="row mt-3">
                            <div class="col-5">
                                <%= f.label :address, "住所" %>
                            </div>
                            <div class="col-7">
                                <%= f.text_area :address %>
                            </div>
                        </div>


                        <div class="row actions mt-3">
                            <div class="col text-right">
                                <%# 変更内容をupdate、マイページにリダイレクト %>
                                <%= f.submit "変更", class: "btn btn-success" %>
                                <%# 退会ページに遷移 %>
                                <%= link_to "退会", cancel_admin_shop_path, class: "btn btn-danger" %>
                          </div>
                        </div>
                    </div>
                </div>
            <% end %>

        </div>

        <div class="col"></div>
    </div>
</div>

app/views/admin/shops/show.html.erb
<div class="container">
	<div class="row">
		<div class="col-8 offset-2 mt-5">
			<h2>マイページ</h2>
			<br>
			<h5>shop情報</h5>
		</div>
	</div>

	<%# 店舗情報 %>
	<div class="row mt-4">

		<%# shop/profile画像 %>
		<div class="col-5 offset-1 text-center">
			<%= attachment_image_tag @shop, :profile_image, format: "jpg", fallback: "no_image.png", size:'230', class: "rounded-circle border"  %>
		</div>

		<%# shop/詳細 %>
		<div class="col-5">
			<div class="row">
				<div class="col">
					<table class="table table-bordered table-hover">
						<tbody>
							<tr>
								<th>アカウント名</th>
								<td>
									<%= @shop.name %>
								</td>
							</tr>
							<tr>
								<th>メールアドレス</th>
								<td>
									<%= @shop.email %>
								</td>
							</tr>
							<tr>
								<th>郵便番号</th>
								<td>
									<%= @shop.postal_code %>
								</td>
							</tr>
							<tr>
								<th>住所</th>
								<td>
									<%= @shop.address %>
								</td>
							</tr>
						</tbody>
					</table>
				</div>
			</div>

			<%# 編集ページに遷移 %>
			<div class="row">
				<div class="col text-right">
					<%= link_to "編集", edit_admin_shop_path, class: "btn btn-primary" %>
				</div>
			</div>
		</div>

		<div class="col"></div>
	</div>

	<%# 取り置き商品一覧ページに遷移 %>
	<div class="row mt-4">
		<div class="col-3 offset-3 text-right">
			<h6>取り置き商品</h6>
		</div>
		<div class="col-3 text-left">
			<%= link_to "取り置き一覧", admin_reservations_path, class: "btn btn-success" %>
		</div>
	</div>

	<%# 来店予約一覧ページに遷移 %>
	<div class="row mt-4">
		<div class="col-3 offset-3 text-right">
			<h6>来店予約</h6>
		</div>
		<div class="col-3">
			<%= link_to "来店予約一覧", admin_bookings_path, class: "btn btn-success" %>
		</div>
	</div>

	<%# お問い合わせ一覧ページに遷移 %>
	<div class="row mt-4">
		<div class="col-3 offset-3 text-right">
			<h6>お問い合わせ</h6>
		</div>
		<div class="col-3">
			<%= link_to "問い合わせ一覧", admin_contacts_path, class: "btn btn-success" %>
		</div>
	</div>

	<div class="row mt-4">
		<div class="col text-right">
			<%= link_to "新規投稿", new_admin_post_image_path, class: "btn btn-primary" %>
		</div>
	</div>

	<%# 投稿一覧 %>
	<div class="row border-top mt-1">
		<% @post_images.each do |ps| %>
			<div class="col mt-4">
				<%= link_to admin_post_image_path(ps.id) do %>
					<%= attachment_image_tag ps, :image, format:"jpg", fallback: "no_image.png", size:'250' %>
				<% end %>
			</div>
		<% end %>
	</div>
</div>