config/routes.rb
Rails.application.routes.draw do
  devise_for :shops, controllers: {
    sessions: 'shops/sessions',
    passwords: 'shops/passwords',
    registrations: 'shops/registrations'
  }
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    passwords: 'users/passwords',
    registrations: 'users/registrations'
  }


  #userサイト
  root 'public/users#top'
  put '/user' => 'public/users#destroy'
  scope module: :public do
    #idが必要ないと考えた為、単数形resource
    resource :user, only: [:show, :edit, :update] do
      collection do
        get 'cancel'
        get 'about'
      end
    end

    resources :post_images, only: [:index, :show] do
      resource :reservations, only: [:create] do
        collection do
          get 'finish'
        end
      end
      resource :comments, only: [:create]
      resource :favorites, only: [:create, :destroy]
    end

    #shop_idが必要だった為、contact/bookingをネスト(6/1)
    resources :shops, only: [:index, :show] do
      resource :contacts, only: [:new, :create] do
        collection do
          get 'finish'
        end
      end
      resources :bookings, only: [:new, :create] do
        collection do
          get 'finish'
        end
      end
    end

  end

  #shopサイト
  namespace :admin do
    #idが必要ないと考えた為、単数形resource
    resource :shop, only: [:show, :edit, :update, :destroy] do
      collection do
        get 'cancel'
      end
    end

    resources :post_images, only: [:new, :create, :show, :edit, :update]

    resources :reservations, only: [:index]

    resources :bookings, only: [:index]

    resources :contacts, only: [:index]
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/post_image.rb
class PostImage < ApplicationRecord

  #relations
  belongs_to :shop
  has_many :favorites, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :reservations, dependent: :destroy
  has_many :tags, dependent: :destroy

  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end

  #画像投稿メソッド
  attachment :image

  #with_optionsを用いてvalidates付与
  with_options presence: true do |pi|
  	pi.validates :shop_id
  	pi.validates :image
  	pi.validates :title
  	pi.validates :body
  	pi.validates :price
  end
end

app/controllers/admin/post_images_controller.rb
class Admin::PostImagesController < ApplicationController
  def new
    @post_image = PostImage.new
  end

  def create
    @post_image = PostImage.new(post_image_params)
    #ログインしている人以外は投稿できない
    @post_image.shop_id = current_shop.id
    #登録内容に不備がある場合はrenderで新規投稿ページに戻る
    if @post_image.save
      tags = Vision.get_image_data(@post_image.image)
      tags.each do |tag|
        @post_image.tags.create(name: tag)
      end
      redirect_to admin_post_image_path(@post_image.id)
    else
      render :new
    end
  end

  def show
    #該当の投稿を取得
    @post_image = PostImage.find(params[:id])
    #ログインしているshopと該当の投稿をしたshopを同意に
    @post_image.shop.id = current_shop.id
  end

  def edit
    @post_image = PostImage.find(params[:id])
  end

  def update
    @post_image = PostImage.find(params[:id])
    @post_image.update(post_image_params)
    redirect_to admin_post_image_path
  end

  private

  def post_image_params
    params.require(:post_image).permit(:title, :body, :image, :price)
  end
end

app/helpers/admin/post_images_helper.rb
module Admin::PostImagesHelper
end

app/views/admin/post_images/edit.html.erb
<div class="container">
	<div class="row">
		<div class="col"></div>

		<div class="col-8 mt-4">
			<div class="row">
				<h2>投稿編集</h2>
			</div>

			<div class="row">
				<%# 画像表示 %>
				<div class="col">
					<div class="row">
						<%= attachment_image_tag @post_image, :image, :fill, 400, 400, format: "jpg", fallback: "no_image.png", size:'300x300' %>
					</div>
				</div>
				<%# 画像ファイル、商品名、金額、紹介文投稿 %>
				<div class="col">
					<%= form_for(@post_image, url: admin_post_image_path(@post_image.id)) do |f| %>
						<%# 画像ファイル投稿 %>
						<div class="row">
							<div class="col-4">
								<%= f.label :image, "画像ファイル" %>
							</div>
							<div class="col-8">
								<%= f.attachment_field :image %>
							</div>
						</div>
						<%# 商品名登録 %>
						<div class="row mt-3">
							<div class="col-4">
								<%= f.label :title, "商品名" %>
							</div>
							<div class="col-8">
								<%= f.text_field :title %>
							</div>
						</div>
						<%# 金額登録 %>
						<div class="row mt-3">
							<div class="col-4">
								<%= f.label :price, "金額" %>
							</div>
							<div class="col-8">
								<%= f.text_field :price %>円
							</div>
						</div>
						<%# 紹介文登録 %>
						<div class="row mt-3">
							<div class="col-4">
								<%= f.label :body, "紹介文" %>
							</div>
						</div>
						<div class="row">
							<div class="col-8">
								<%= f.text_area :body, size: "40x5" %>
							</div>
						</div>
						<%# 編集保存ボタン %>
						<div class="row mt-3">
							<div class="col text-right">
								<%= f.submit "変更", class: "btn btn-success" %>
							</div>
						</div>
					<% end %>
				</div>
			</div>
		</div>

		<div class="col"></div>
	</div>
</div>

app/views/admin/post_images/new.html.erb
<div class="container">
	<div class="row">
		<div class="col"></div>

		<div class="col-8 mt-4">
			<div class="row">
				<h2>新規投稿</h2>
			</div>

			<div class="row">
				<%# 画像表示 %>
				<div class="col">
					<div class="row">
						<%= attachment_image_tag @post_image, :image, :fill, 400, 400, format: "jpg", fallback: "no_image.png", size:'300x300' %>
					</div>
				</div>
				<%# 画像ファイル、商品名、金額、紹介文投稿 %>
				<div class="col">
					<%= form_for(@post_image, url: admin_post_images_path) do |f| %>
						<%# 画像ファイル投稿 %>
						<div class="row">
							<div class="col-4">
								<%= f.label :image, "画像ファイル" %>
							</div>
							<div class="col-8">
								<%= f.attachment_field :image %>
							</div>
						</div>
						<%# 商品名登録 %>
						<div class="row mt-3">
							<div class="col-4">
								<%= f.label :title, "商品名" %>
							</div>
							<div class="col-8">
								<%= f.text_field :title %>
							</div>
						</div>
						<%# 金額登録 %>
						<div class="row mt-3">
							<div class="col-4">
								<%= f.label :price, "金額" %>
							</div>
							<div class="col-8">
								<%= f.text_field :price %>円
							</div>
						</div>
						<%# 紹介文登録 %>
						<div class="row mt-3">
							<div class="col-4">
								<%= f.label :body, "紹介文" %>
							</div>
						</div>
						<div class="row">
							<div class="col-8">
								<%= f.text_area :body, size: "40x5" %>
							</div>
						</div>
						<%# 投稿ボタン %>
						<div class="row mt-3">
							<div class="col text-right">
								<%= f.submit "投稿", class: "btn btn-primary" %>
							</div>
						</div>
					<% end %>
				</div>
			</div>
		</div>

		<div class="col"></div>
	</div>
</div>

app/views/admin/post_images/show.html.erb
<div class="container">
	<div class="row">
		<div class="col"></div>

		<div class="col-8 mt-4">
			<div class="row">
				<h2>投稿詳細</h2>
			</div>

			<div class="row mt-3">
				<div class="col">
					<%# 商品画像を表示 %>
					<div>
						<%= attachment_image_tag @post_image, :image, format: "jpg", fallback: "no_image.png", size: "300" %>
					</div>
					<%# vision_apiを用いて画像を認識しタグづけ %>
					<h6 class="mt-2">
						<% @post_image.tags.each do |tag| %>
                			<span class="badge badge-info">
                				<%= tag.name %>
                			</span>
              			<% end %>
					</h6>
				</div>

				<div class="col">
					<div class="row">
						<%# 商品情報を表示 %>
						<table class="table table-hover table-bordered">
							<tbody>
								<tr>
									<th>
										<%= "店舗名" %>
									</th>
									<td>
										<%= current_shop.name %>
									</td>
								</tr>
								<tr>
									<th>
										<%= "商品名" %>
									</th>
									<td>
										<%= @post_image.title %>
									</td>
								</tr>
								<tr>
									<th>
										<%= "金額" %>
									</th>
									<td>
										<%= @post_image.price %>円
									</td>
								</tr>
								<tr>
									<th>
										<%= "紹介文" %>
									</th>
									<td>
										<%= @post_image.body %>
									</td>
								</tr>
							</tbody>
						</table>
					</div>

					<div class="row">
						<div class="col text-right">
							<%# 該当の編集ページの遷移 %>
							<%= link_to "編集", edit_admin_post_image_path, class: "btn btn-primary" %>
						</div>
					</div>

				</div>
			</div>
		</div>

		<div class="col"></div>
	</div>
</div>