config/routes.rb
Rails.application.routes.draw do
  devise_for :shops, controllers: {
    sessions: 'shops/sessions',
    passwords: 'shops/passwords',
    registrations: 'shops/registrations'
  }
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    passwords: 'users/passwords',
    registrations: 'users/registrations'
  }


  #userサイト
  root 'public/users#top'
  put '/user' => 'public/users#destroy'
  scope module: :public do
    #idが必要ないと考えた為、単数形resource
    resource :user, only: [:show, :edit, :update] do
      collection do
        get 'cancel'
        get 'about'
      end
    end

    resources :post_images, only: [:index, :show] do
      resource :reservations, only: [:create] do
        collection do
          get 'finish'
        end
      end
      resource :comments, only: [:create]
      resource :favorites, only: [:create, :destroy]
    end

    #shop_idが必要だった為、contact/bookingをネスト(6/1)
    resources :shops, only: [:index, :show] do
      resource :contacts, only: [:new, :create] do
        collection do
          get 'finish'
        end
      end
      resources :bookings, only: [:new, :create] do
        collection do
          get 'finish'
        end
      end
    end

  end

  #shopサイト
  namespace :admin do
    #idが必要ないと考えた為、単数形resource
    resource :shop, only: [:show, :edit, :update, :destroy] do
      collection do
        get 'cancel'
      end
    end

    resources :post_images, only: [:new, :create, :show, :edit, :update]

    resources :reservations, only: [:index]

    resources :bookings, only: [:index]

    resources :contacts, only: [:index]
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord

  #relations
  belongs_to :user
  belongs_to :shop

  #with_optionsを用いてvalidates付与
  with_options presence: true do |b|
  	b.validates :user_id
  	b.validates :shop_id
  	b.validates :datetime
  end

end

app/models/comment.rb
class Comment < ApplicationRecord

  #relations
  belongs_to :user
  belongs_to :post_image

  #with_optionsを用いてvalidates付与
  with_options presence: true do |c|
  	c.validates :user_id
  	c.validates :post_image_id
  	c.validates :comment
  end

end

app/models/contact.rb
class Contact < ApplicationRecord

  #relations
  belongs_to :user
  belongs_to :shop

  #with_optionsを用いてvalidates付与
  with_options presence: true do |c|
  	c.validates :user_id
  	c.validates :shop_id
  	c.validates :body
  end

end

app/models/favorite.rb
class Favorite < ApplicationRecord
  #relations
  belongs_to :user
  belongs_to :post_image

  #with_optionsを用いてvalidates付与
  with_options presence: true do |f|
  	f.validates :user_id
  	f.validates :post_image_id
  end

end

app/models/post_image.rb
class PostImage < ApplicationRecord

  #relations
  belongs_to :shop
  has_many :favorites, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :reservations, dependent: :destroy
  has_many :tags, dependent: :destroy

  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end

  #画像投稿メソッド
  attachment :image

  #with_optionsを用いてvalidates付与
  with_options presence: true do |pi|
  	pi.validates :shop_id
  	pi.validates :image
  	pi.validates :title
  	pi.validates :body
  	pi.validates :price
  end
end

app/models/reservation.rb
class Reservation < ApplicationRecord

  #relations
  belongs_to :user
  belongs_to :post_image
  belongs_to :shop

  #with_optionsを用いてvalidates付与
  with_options presence: true do |r|
  	r.validates :user_id
  	r.validates :post_image_id
  	r.validates :title
  	r.validates :user_name
  	r.validates :user_email
  	r.validates :shop_id
  end

end

app/models/shop.rb
class Shop < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  #relations
  has_many :post_images, dependent: :destroy
  has_many :contacts, dependent: :destroy
  has_many :bookings, dependent: :destroy
  has_many :reservations, dependent: :destroy

  #画像投稿メソッド
  attachment :profile_image

  #with_optionsを用いてvalidates付与
  with_options presence: true do |s|
  	s.validates :name
  	s.validates :postal_code
  	s.validates :address
  end
  #日本の郵便番号は7桁
  validates :postal_code, format: { with: /\A\d{7}\z/}


end

app/models/tag.rb
class Tag < ApplicationRecord
	#relations
	belongs_to :post_image
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  #relation
  has_many :contacts, dependent: :destroy
  has_many :bookings, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :reservations, dependent: :destroy

  #with_optionsを用いてvalidates付与
  with_options presence: true do |u|
  	u.validates :name
  	u.validates :phone_number
  end

  #日本の電話番号は10か11桁
  validates :phone_number, format: { with: /\A\d{10,11}\z/}

end

app/controllers/admin/bookings_controller.rb
class Admin::BookingsController < ApplicationController
  def index
  	#whereを用いて、bookingに保存されているshop_idからログインしているshop.idを拾う
  	#.order(created_at: :desc)で新着順に
  	@bookings = Booking.where(shop_id: current_shop.id).order(created_at: :desc)
  end
end

app/controllers/admin/contacts_controller.rb
class Admin::ContactsController < ApplicationController
	def index
	  	#whereを用いて、bookingに保存されているshop_idからログインしているshop.idを拾う
  		#.order(created_at: :desc)で新着順に
	  	@contacts = Contact.where(shop_id: current_shop.id).order(created_at: :desc)
	end
end

app/controllers/admin/shops_controller.rb
class Admin::ShopsController < ApplicationController
  def show
  	@shop = Shop.find(current_shop.id)
    #.order(created_at: :desc)で新着順に
    @post_images = PostImage.where(shop_id: current_shop.id).order(created_at: :desc)
  end

  def edit
  	@shop = Shop.find(current_shop.id)
  end

  def update
  	@shop = Shop.find(current_shop.id)
  	@shop.update(shop_params)
  	redirect_to admin_shop_path
  end

  def cancel
  end

  private

  def shop_params
  	params.require(:shop).permit(:name, :email, :postal_code, :address, :profile_image)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

	before_action :configure_permitted_parameters, if: :devise_controller?

	protected
	#deviseのストロングパラメータ記述
	def configure_permitted_parameters
		devise_parameter_sanitizer.permit(:sign_up, keys:[:name, :phone_number, :postal_code, :address])
	end

end

app/helpers/admin/bookings_helper.rb
module Admin::BookingsHelper
end

app/helpers/admin/contacts_helper.rb
module Admin::ContactsHelper
end

app/helpers/admin/post_images_helper.rb
module Admin::PostImagesHelper
end

app/helpers/admin/reservations_helper.rb
module Admin::ReservationsHelper
end

app/helpers/admin/shops_helper.rb
module Admin::ShopsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
    <head>
        <title>Youseid</title>
        <%= csrf_meta_tags %>
        <%= csp_meta_tag %>

        <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
        <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    </head>

    <body>
        <header id="header">
            <nav class="navbar navbar-expand-lg navbar-light bg-light">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item">
                        <%# ロゴのリンク先もECサイトと管理人サイトで分けます。%>
                        <% if request.url.include?('admin') %>  <%# 今のURLに'admin'が入っているかどうかでどちらのサイトなのかを識別 %>
                            <%# 管理人サイトの場合 %>
                            <a class="navbar-brand" href="/admin/shop">
                                <%= image_tag 'logo.png', :size => '65' %>
                            </a>
                        <% else %>
                            <%# ECサイトの場合 %>
                            <a class="navbar-brand" href="/">
                                <%= image_tag 'logo.png', :size => '65' %>
                            </a>
                        <% end %>
                    </li>
                </ul>
                <ul class="navbar-nav">
                    <%# 今のURLにadminが入っているかどうかでどちらのサイトなのかを識別 %>
                    <% if request.url.include?('admin') %>
                        <%# 管理者サイト かつ 管理人でログインしている場合 %>
                        <% if shop_signed_in? %>
                            <li class="nav-item nav-link">
                                <%= link_to "マイページ", admin_shop_path, :style=>"color:black;" %>
                            </li>
                            <li class="nav-item nav-link">
                                <%= link_to "新規投稿", new_admin_post_image_path, :style=>"color:black;" %>
                            </li>
                            <li class="nav-item nav-link">
                                <%= link_to "ログアウト", destroy_shop_session_path, method: :delete, :style=>"color:black;" %>
                            </li>
                        <%# 管理者サイト かつ 管理人でログインしていない場合 %>
                        <% else %>
                            <li class="nav-item nav-link">
                                <%= link_to "about", about_user_path, :style=>"color:black;" %>
                            </li>
                        <% end %>
                    <%# ECサイト かつ 会員でログインしている場合 %>
                    <% elsif user_signed_in? %>
                        <li class="nav-item nav-link">
                            <%= link_to "マイページ", "/user", :style=>"color:black;" %>
                        </li>
                        <li class="nav-item nav-link">
                            <%= link_to "商品一覧", post_images_path, :style=>"color:black;" %>
                        </li>
                        <li class="nav-item nav-link">
                            <%= link_to "ログアウト", destroy_user_session_path, method: :delete, :style=>"color:black;" %>
                        </li>
                    <%# ECサイト かつ 会員でログインしていない場合 %>
                    <% else %>
                        <li class="nav-item nav-link">
                            <%= link_to "about", about_user_path, :style=>"color:black;" %>
                        </li>
                    <% end %>
                </ul>
            </nav>
        </header><!-- /header -->
        <%= yield %>
    </body>
</html>